import { defineConfig } from "vite";
import handlebars from "vite-plugin-handlebars";
import { resolve } from "path";

export default defineConfig({
  server: {
    port: 3000,
  },
  preview: {
    port: 3000,
  },
  resolve: {
    alias: {
      "@": resolve(__dirname, "src"),
    },
  },
  root: resolve(__dirname, "src"),
  build: {
    outDir: resolve(__dirname, "dist"),
    rollupOptions: {
      input: {
        main: resolve(__dirname, "src/index.html"),
        login: resolve(__dirname, "src/login.html"),
        register: resolve(__dirname, "src/register.html"),
        profile: resolve(__dirname, "src/profile.html"),
        404: resolve(__dirname, "src/404.html"),
        500: resolve(__dirname, "src/500.html"),
      },
    },
    emptyOutDir: true,
  },
  plugins: [
    handlebars({
      partialDirectory: [
        resolve(__dirname, "src/partials"),
        resolve(__dirname, "src/layouts"),
      ],
      context: {
        users: [
          {
            id: "user1",
            name: "Андрей",
            isActive: true,
            avatarUrl: "./assets/images/chat/users/1.png",
            lastMessage: "Друзья, у меня для вас особенный выпуск новостей!",
            isOnline: true,
            isSeen: true,
            lastMessageTime: "10:49",
            unreadCount: 0,
          },
          {
            id: "user2",
            name: "Илья",
            isActive: false,
            avatarUrl: "./assets/images/chat/users/2.png",
            lastMessage: "Изображение",
            isOnline: false,
            isSeen: false,
            lastMessageTime: "Пт",
            unreadCount: 2,
          },
          {
            id: "user3",
            name: "Киноклуб",
            isActive: false,
            avatarUrl: "./assets/images/chat/users/3.png",
            lastMessage: "Круто!",
            isOnline: false,
            isSeen: true,
            lastMessageTime: "1 Мая 2020",
            unreadCount: 0,
          },
          {
            id: "user4",
            name: "тет-а-теты",
            isActive: false,
            avatarUrl: "./assets/images/chat/users/4.png",
            lastMessage:
              "Так увлёкся работой по курсу, что забыл анонсировать.",
            isOnline: false,
            isSeen: false,
            lastMessageTime: "15:12",
            unreadCount: 5,
          },
          {
            id: "user5",
            name: "1, 2, 3",
            isActive: false,
            avatarUrl: "./assets/images/chat/users/5.png",
            lastMessage: "Когда встретимся?",
            isOnline: true,
            isSeen: false,
            lastMessageTime: "Вчера",
            unreadCount: 3,
          },
          {
            id: "user6",
            name: "Design Destroyer",
            isActive: false,
            avatarUrl: "./assets/images/chat/users/6.png",
            lastMessage: "Ок, договорились.",
            isOnline: true,
            isSeen: true,
            lastMessageTime: "12:21",
            unreadCount: 0,
          },
          {
            id: "user7",
            name: "Сергей",
            isActive: false,
            avatarUrl: "./assets/images/chat/users/7.png",
            lastMessage: "Пришли файл, пожалуйста.",
            isOnline: false,
            isSeen: false,
            lastMessageTime: "Чт",
            unreadCount: 1,
          },
          {
            id: "user8",
            name: "Лена",
            isActive: false,
            avatarUrl: "./assets/images/chat/users/8.png",
            lastMessage: "Отправила фото.",
            isOnline: false,
            isSeen: false,
            lastMessageTime: "Ср",
            unreadCount: 7,
          },
          {
            id: "user9",
            name: "Рабочий чат",
            isActive: false,
            avatarUrl: "./assets/images/chat/users/9.png",
            lastMessage: "Не забудьте про созвон в понедельник!",
            isOnline: false,
            isSeen: false,
            lastMessageTime: "Пн",
            unreadCount: 12,
          },
          {
            id: "user10",
            name: "Design Destroyer",
            isActive: false,
            avatarUrl: "./assets/images/chat/users/1.png",
            lastMessage: "Ок, договорились.",
            isOnline: true,
            isSeen: true,
            lastMessageTime: "12:21",
            unreadCount: 0,
          },
          {
            id: "user11",
            name: "Сергей",
            isActive: false,
            avatarUrl: "./assets/images/chat/users/2.png",
            lastMessage: "Пришли файл, пожалуйста.",
            isOnline: false,
            isSeen: false,
            lastMessageTime: "Чт",
            unreadCount: 1,
          },
          {
            id: "user12",
            name: "Лена",
            isActive: false,
            avatarUrl: "./assets/images/chat/users/3.png",
            lastMessage: "Отправила фото.",
            isOnline: false,
            isSeen: false,
            lastMessageTime: "Ср",
            unreadCount: 7,
          },
          {
            id: "user13",
            name: "Рабочий чат",
            isActive: false,
            avatarUrl: "./assets/images/chat/users/4.png",
            lastMessage: "Не забудьте про созвон в понедельник!",
            isOnline: false,
            isSeen: false,
            lastMessageTime: "Пн",
            unreadCount: 12,
          },
        ],
        messages: [
          {
            date: "19 июня",
            items: [
              {
                isMine: false,
                text: "Привет! Смотри, тут всплыл интересный кусок лунной космической истории — НАСА в какой-то момент попросила Хассельблад адаптировать модель SWC для полетов на Луну.",
                image: null,
                time: "11:56",
                isSeen: true,
              },
              {
                isMine: false,
                text: null,
                image: "./assets/images/chat/photos/1.png",
                time: "11:56",
                isSeen: true,
              },
            ],
          },
          {
            date: "20 июня",
            items: [
              {
                isMine: false,
                text: "Хассельблад в итоге адаптировал SWC для космоса, но что-то пошло не так и на ракету они так никогда и не попали. Всего их было произведено 25 штук, одну из них недавно продали на аукционе за 45000 евро.",
                image: null,
                time: "11:59",
                isSeen: true,
              },
              {
                isMine: true,
                text: "Круто!",
                image: null,
                time: "12:56",
                isSeen: false,
              },
            ],
          },
        ],
        profile: {
          first_name: "Андрей",
          second_name: "Петухов",
          display_name: "Android",
          login: "andrystory",
          phone: "+7 (999) 012-52-60",
          avatar: "./assets/images/chat/users/1.png",
          email: "pochta@yandex.ru",
        },
      },
    }),
  ],
  css: {
    preprocessorOptions: {
      scss: {
        additionalData: `@use '@/styles/helpers' as *;`,
      },
    },
  },
});
